/*
* generated by Xtext
*/
package org.boomslang.wireframesketcher.model.xtext;

import org.eclipse.xtext.util.Modules2;
import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ScreenStandaloneSetup extends ScreenStandaloneSetupGenerated{

	public static void doSetup() {
		new ScreenStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new org.boomslang.wireframesketcher.model.xtext.ScreenRuntimeModule(), new org.boomslang.wireframesketcher.model.xtext.ScreenGeneratorStandaloneModule()));
	}

}

